version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production

  requests_service:
    build: .
    volumes:
      - .:/app
    command: python /app/requests_worker.py
    entrypoint: ["python", "/app/requests_worker.py"] 